### PR TITLE
#21 Add release packages and metadata

### PR DESCRIPTION
**Pull request by mpostelnicu**
Hi, please review this and see the TODO elements. We need to update
- publisher ID
- scheme
- choose a license for the published data https://opendefinition.org/licenses/
- update publication policy http://standard.open-contracting.org/latest/en/implementation/publication_policy/

### CODE REVIEW

**Comment by dc-coder** [comment]
For the licenses, I checked on the open data site of bandung city. All of ~1.5K datasets use Creative Commons Attribution (here is link http://data.bandung.go.id/dataset?license_id=cc-by&_organization_limit=0)

@bdgcoder do you think this is good for @mpostelnicu to use ?

**Comment by dc-coder** [comment]
For the publication policy document,  let me try to get some help from Abdou.

@fabregas1 - do you think you can help generating content for this:
https://raw.githubusercontent.com/OC-Bandung/newbirms/e20ae1f932f6e2600cc5eed18d5cb48bc1477393/public/api/publication-policy.txt

**Comment by mpostelnicu** [comment]
@fabregas1 @bdgcoder @dc-coder  any progress here? we should merge this too, so we have packages

**Comment by fabregas1** [comment]
Zacky suggests to use the budget account code of Bandung's procurement unit (4.05.4.05.02.08).
The issuer of the budget account code is the Ministry of Finance of the Republic of Indonesia (Kementerian Keuangan).

**Comment by mpostelnicu** [comment]
new URLs available
get packages for each year: `/api/packages/year/[year]`

example for 2016 https://birms.bandung.go.id/beta/api/packages/year/2016

This will link to OCDS compliant package metadata, along embedded releases

example package URL
https://birms.bandung.go.id/beta/api/package/ocds-afzrfb-s-2016-3662192

**Comment by bdgcoder** [comment]
I have been update online server. You can check the update.

**Pull request merged**
